# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy application code
COPY . /app

# Install UV CLI for dependency management
RUN pip install --no-cache-dir uv

# Set working directory to MCP server
WORKDIR /app/whatsapp-mcp-server

# Default entrypoint to run the MCP server
ENTRYPOINT ["uv", "run", "main.py"]
